const constants = {
    LOGIN: "LOGIN",
    LOGIN_SUCCEDED: "LOGIN_SUCCEDED",
    LOGIN_FAILED: "LOGIN_FAILED",

    LOGOUT: 'LOGOUT',
    LOGOUT_SUCCEDED: 'LOGOUT_SUCCEDED',
    LOGOUT_FAILED: 'LOGOUT_FAILED',

    REGISTER: "REGISTER",
    REGISTER_SUCCEDED: "REGISTER_SUCCEDED",
    REGISTER_FAILED: "REGISTER_FAILED",

    FETCHUSERS: "FETCHUSERS",
    FETCHUSERS_SUCCEDED: "FETCHUSERS_SUCCEDED",
    FETCHUSERS_FAILED: "FETCHUSERS_FAILED",
}

export default constants